### ISSUE TITLE
Jobs in queue not getting handled

### ISSUE THREAD

**Issue by timgrossmann** [thisandagain/fork-pool#4]
Hey,
I hope this project is still intact.
Really like the approach and API you're providing here.

The thing is, it seems like the jobs are not retrived from the queue once every core worked on one of the tasks.

I'm enqueuing 10 tasks in a loop, 8 of them get executed (I see that there are 10 jobs enqueued).
I'm adding all of the jobs as a Promise to a list which will then be returned using Promise.all().

Somehow it's not executing more than 8 of the 10 tasks, I waited for quite a while already and hope that it would go on and execute further tasks, but It does not do that.

Do you have any idea what the problem could be?

**Comment by timgrossmann** [comment]
@mubaidr Yeah, I thought about that, too.
I'm definitely resolving those promise though.

It's working if I'm pushing less than 9 elements into the pool.

Do I have to call some other method in order to release those tasks from the pool?

I'll try to use the library with some simpler logic and check if it has the same behaviour.

Thanks for the response 😉

**Comment by mubaidr** [comment]
It looks like you might have to send message from client/child process to consider its done.

**Comment by timgrossmann** [comment]
@mubaidr Yeah I'm actually also doing that.
Maybe it's a problem that I'm exiting the forked process after it finished it worked and I'm sending the message to the parent since my child process somehow did not exit on its own.

**Comment by mubaidr** [comment]
This code base is not being updated regularly and underlying library [node-pool](https://github.com/coopernurse/node-pool#readme) has changed so much. You might want to look something better more maintained.

**Comment by timgrossmann** [comment]
@mubaidr you're absolutely right, I saw that just thought maybe it's still working the same way.

Thank you very much for the support!
